import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function GET(request: NextRequest) {
  try {
    const modelosData = [
      {
        id: "35",
        nome: "Seguradora",
        arquivo: "{\"agendaMsg\":[],\"assinatura\":{\"is_select\":true,\"nome\":\"Hebrain\"},\"categoria\":[],\"ccList\":[],\"contatos\":[],\"crm_peformace\":{\"abas\":15,\"inbox\":15},\"darkMode\":[],\"dataVerif\":\"08/14/2023\",\"events\":[],\"finalizar\":{\"arquivar\":false,\"envTxt\":true,\"txt\":\"*_#Atendimento Finalizado_*\\n\"},\"guardaMsg\":[{\"categoria\":\"\",\"clicked\":0,\"config\":{\"aba\":\"Achou Preco Alto\",\"arquivar\":false,\"etiqueta\":\"\"},\"id\":\"33c38719-104d-46e0-8036-77d264960c62\",\"mensagem\":\"Compreendo [CLIENTE]! Quando você diz caro, você está comparando com o que especificamente? Só pra eu entender e poder te ajudar mesmo.\",\"titulo\":\"Negociação\",\"type\":\"txt\"},{\"categoria\":\"\",\"clicked\":0,\"config\":{\"aba\":\"Leads\",\"arquivar\":false,\"etiqueta\":\"\"},\"id\":\"36bcdb5c-cec3-4fc0-ad63-d1191b77263a\",\"mensagem\":\"Olá [CLIENTE], meu nome é [VENDEDOR]. \\nTudo bem? \\nÉ uma alegria para mim poder te ajudar.😀\",\"titulo\":\"Saudação\",\"type\":\"txt\"}],\"initSystem\":true,\"keyCopy\":\"hebrainwatidy\",\"lang\":\"pt\",\"license\":\"KNzVIL+5KBj6JDUF2sQmUytpIVcGQnQ=--Rd4M3qsVinPmSdym--VeITrRPZtbnyet1oIvEatA==\",\"menuItems\":[{\"icon\":\"all\",\"id\":\"edit_tabs\",\"title\":\"Configurações de abas\"},{\"icon\":\"notifications\",\"id\":\"notifications\",\"title\":\"Notificações\"},{\"icon\":\"campaign\",\"id\":\"campaign\",\"title\":\"Envios em Massa\"},{\"icon\":\"automatic_bot\",\"id\":\"automatic_bot\",\"title\":\"Robo de automação\"},{\"icon\":\"cog\",\"id\":\"settings\",\"title\":\"Configurações\"}],\"notes\":[],\"notifications\":[],\"perfil\":[],\"privacySettings\":{\"allMsgs\":false,\"lastMsg\":false,\"mediaGallery\":false,\"mediaPreview\":false,\"names\":false,\"profilePic\":false},\"systemTabs\":[{\"img\":\"all\",\"tag\":\"tab_all\",\"type\":\"system\"},{\"img\":\"unread\",\"tag\":\"tab_unread\",\"type\":\"system\"},{\"img\":\"groups\",\"tag\":\"tab_groups\",\"type\":\"system\"},{\"img\":\"1_1\",\"tag\":\"tab_1_1\",\"type\":\"system\"}],\"userTabs\":[{\"chats\":[],\"tag\":\"Leads\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Seguro Auto\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Seguro Caminhoes\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Seguro Residencial\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Seguro Comercial\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Proposta Enviada\",\"type\":\"user\"}],\"valNegocio\":[],\"zoomCRM\":100}",
        descricao: "Nossa ferramenta é uma exelente solução para você que precisa organizar seus clientes de sua seguradora. Com um funil simples e funcional você pode ter uma visão de todos seus contatos e assim oportunidades maiores de realizar sua venda. Usar seu whatsapp web com nossa solução trará uma nova experiência para suas vendas. Ah lembrando que você pode remover ou incluir novas abas ems eu crm além de criar respostas rápidas personalizadas para agilziar o seu atendimento."
      },
      {
        id: "33",
        nome: "Imobiliária",
        arquivo: "{\"userTabs\":[{\"chats\":[],\"id\":\"Sentenciado\",\"tag\":\"Novo Lead\",\"type\":\"user\"},{\"chats\":[],\"id\":\"Tributario\",\"tag\":\"Casa\",\"type\":\"user\"},{\"chats\":[],\"id\":\"Trabalhista\",\"tag\":\"Apartamento\",\"type\":\"user\"},{\"chats\":[],\"id\":\"Civel\",\"tag\":\"Lote\",\"type\":\"user\"},{\"chats\":[],\"id\":\"Criminal\",\"tag\":\"Rural\",\"type\":\"user\"},{\"chats\":[],\"id\":\"Audiencias\",\"tag\":\"Lançamento\",\"type\":\"user\"},{\"chats\":[],\"id\":\"Orcamento Enviado\",\"tag\":\"Negociando\",\"type\":\"user\"}],\"guardaMsg\":[{\"categoria\":\"\",\"clicked\":0,\"config\":{\"aba\":\"Achou Preco Alto\",\"arquivar\":false,\"etiqueta\":\"\"},\"id\":\"33c38719-104d-46e0-8036-77d264960c62\",\"mensagem\":\"Compreendo [CLIENTE]! Quando você diz caro, você está comparando com o que especificamente? Só pra eu entender e poder te ajudar mesmo.\",\"titulo\":\"Negociação\",\"type\":\"txt\"},{\"categoria\":\"\",\"clicked\":0,\"config\":{\"aba\":\"Leads\",\"arquivar\":false,\"etiqueta\":\"\"},\"id\":\"36bcdb5c-cec3-4fc0-ad63-d1191b77263a\",\"mensagem\":\"Olá [CLIENTE], meu nome é [VENDEDOR]. \\nTudo bem? \\nÉ uma alegria para mim poder te ajudar.😀\",\"titulo\":\"Saudação\",\"type\":\"txt\"}],\"categoria\":[]}",
        descricao: "Nosso CRM imobiliário é a solução perfeita para transformar a gestão de propriedades em uma experiência ágil e eficiente. Com recursos avançados e intuitivos, você terá o controle completo sobre suas transações imobiliárias. Desde casas de alto padrão até imóveis comerciais, nosso CRM oferece organização impecável, acompanhamento em tempo real, integração com ferramentas essenciais e uma visão panorâmica das negociações. Simplifique a gestão de imóveis, aumente a produtividade da sua equipe e ofereça um atendimento personalizado e eficaz aos seus clientes, tudo isso em um ambiente amigável e prático."
      },
      {
        id: "36",
        nome: "Agência de Veículos",
        arquivo: "{\"agendaMsg\":[],\"assinatura\":{\"nome\":null},\"categoria\":[{\"format\":\"star\",\"hexColor\":\"#dd371c\",\"id\":\"a42cae3a-f2b2-47cf-bd26-63dec728f1f2\",\"name\":\"NEGOCIAÇÃO\"},{\"format\":\"star\",\"hexColor\":\"#efaa72\",\"id\":\"ccaef770-c911-4d9f-9f8c-4f6cc8cd4c7c\",\"name\":\"PROP DE VALOR📝\"},{\"format\":\"star\",\"hexColor\":\"#c0625d\",\"id\":\"797e1b28-a643-47aa-b829-ced24e6acaad\",\"name\":\"INTERESSE🏹\"},{\"format\":\"star\",\"hexColor\":\"#1a11a6\",\"id\":\"f8e2ac78-2a52-42fb-908d-83996cac6a61\",\"name\":\"MAPEAMENTO✍️\"}],\"ccList\":[],\"contatos\":[],\"crm_peformace\":{\"abas\":15,\"inbox\":15},\"darkMode\":[],\"dataVerif\":\"08/28/2023\",\"events\":[],\"finalizar\":{\"arquivar\":false,\"envTxt\":true,\"txt\":\"*_#Atendimento Finalizado_*\\n\"},\"guardaMsg\":[],\"initSystem\":true,\"keyCopy\":\"Valter-free-testes\",\"lang\":\"pt\",\"license\":\"xYuBAYwpqPg998vkYOtY1kN6Z728Zy+8yYTTog==--rt32B5+VGQRIIbdR--PCNfiqq5iMDAeo3QNXpQIg==\",\"menuItems\":[],\"notes\":[],\"notifications\":[],\"perfil\":[],\"privacySettings\":{\"allMsgs\":false,\"lastMsg\":false,\"mediaGallery\":false,\"mediaPreview\":false,\"names\":false,\"profilePic\":false},\"systemTabs\":[{\"img\":\"all\",\"tag\":\"tab_all\",\"type\":\"system\"},{\"img\":\"unread\",\"tag\":\"tab_unread\",\"type\":\"system\"},{\"img\":\"groups\",\"tag\":\"tab_groups\",\"type\":\"system\"},{\"img\":\"1_1\",\"tag\":\"tab_1_1\",\"type\":\"system\"}],\"userTabs\":[{\"chats\":[],\"tag\":\"Mapeamento\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Interesse\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Proposta de Valor\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Negociacao\",\"type\":\"user\"}],\"valNegocio\":[],\"zoomCRM\":100}",
        descricao: "Nosso funil para agência de veículos vai te ajudar a organizar melhor suas oportunidades de venda, classificando seus clientes pelo interesse específico e assim aproximando oportunidade de vendas a seus leads novos ou antigos. Com certeza o nível de organização do seu negócio evolui, aproximando novas vendas ao seu negócio! Não se esqueça de criar respostas personalizadas ao seu seguimento, agilizando assim o seu atendimento!"
      },
      {
        id: "37",
        nome: "Delivery",
        arquivo: "{\"agendaMsg\":[],\"assinatura\":{\"is_select\":true,\"nome\":\"Hebrain\"},\"categoria\":[],\"ccList\":[],\"contatos\":[],\"crm_peformace\":{\"abas\":15,\"inbox\":15},\"darkMode\":[],\"dataVerif\":\"08/14/2023\",\"events\":[],\"finalizar\":{\"arquivar\":false,\"envTxt\":true,\"txt\":\"*_#Atendimento Finalizado_*\\n\"},\"guardaMsg\":[{\"categoria\":\"\",\"clicked\":0,\"config\":{\"aba\":\"Achou Preco Alto\",\"arquivar\":false,\"etiqueta\":\"\"},\"id\":\"33c38719-104d-46e0-8036-77d264960c62\",\"mensagem\":\"Compreendo [CLIENTE]! Quando você diz caro, você está comparando com o que especificamente? Só pra eu entender e poder te ajudar mesmo.\",\"titulo\":\"Negociação\",\"type\":\"txt\"},{\"categoria\":\"\",\"clicked\":0,\"config\":{\"aba\":\"Leads\",\"arquivar\":false,\"etiqueta\":\"\"},\"id\":\"36bcdb5c-cec3-4fc0-ad63-d1191b77263a\",\"mensagem\":\"Olá [CLIENTE], meu nome é [VENDEDOR]. \\nTudo bem? \\nÉ uma alegria para mim poder te ajudar.😀\",\"titulo\":\"Saudação\",\"type\":\"txt\"}],\"initSystem\":true,\"keyCopy\":\"hebrainwatidy\",\"lang\":\"pt\",\"license\":\"KNzVIL+5KBj6JDUF2sQmUytpIVcGQnQ=--Rd4M3qsVinPmSdym--VeITrRPZtbnyet1oIvEatA==\",\"menuItems\":[{\"icon\":\"all\",\"id\":\"edit_tabs\",\"title\":\"Configurações de abas\"},{\"icon\":\"notifications\",\"id\":\"notifications\",\"title\":\"Notificações\"},{\"icon\":\"campaign\",\"id\":\"campaign\",\"title\":\"Envios em Massa\"},{\"icon\":\"automatic_bot\",\"id\":\"automatic_bot\",\"title\":\"Robo de automação\"},{\"icon\":\"cog\",\"id\":\"settings\",\"title\":\"Configurações\"}],\"notes\":[],\"notifications\":[],\"perfil\":[],\"privacySettings\":{\"allMsgs\":false,\"lastMsg\":false,\"mediaGallery\":false,\"mediaPreview\":false,\"names\":false,\"profilePic\":false},\"systemTabs\":[{\"img\":\"all\",\"tag\":\"tab_all\",\"type\":\"system\"},{\"img\":\"unread\",\"tag\":\"tab_unread\",\"type\":\"system\"},{\"img\":\"groups\",\"tag\":\"tab_groups\",\"type\":\"system\"},{\"img\":\"1_1\",\"tag\":\"tab_1_1\",\"type\":\"system\"}],\"userTabs\":[{\"chats\":[],\"tag\":\"Segunda\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Terca\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Quarta\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Quinta\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Sexta\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Sabado\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Domingo\",\"type\":\"user\"}],\"valNegocio\":[],\"zoomCRM\":100}",
        descricao: "Com nossa ferramenta você pode organizar seus clientes conforme o comprtamento de compra deles. Como exemplo montamos um funil para separar os clientes que compram de acordo com o dia da semana. Desta forma fomentar como exemplo um cliente que comprou na sexta feira, enviando uma mensagem na sexta feira de outra semana oferecndo um desconto para adquirir pode ser uma boa alternativa de vender mais. Lembrando que você pode montar seu funil como desejar removendo ou adicionando novas abas."
      },
      {
        id: "38",
        nome: "Agência de Viagens",
        arquivo: "{\"agendaMsg\":[],\"assinatura\":{\"is_select\":true,\"nome\":\"Hebrain\"},\"categoria\":[],\"ccList\":[],\"contatos\":[],\"crm_peformace\":{\"abas\":15,\"inbox\":15},\"darkMode\":[],\"dataVerif\":\"08/14/2023\",\"events\":[],\"finalizar\":{\"arquivar\":false,\"envTxt\":true,\"txt\":\"*_#Atendimento Finalizado_*\\n\"},\"guardaMsg\":[{\"categoria\":\"\",\"clicked\":0,\"config\":{\"aba\":\"Achou Preco Alto\",\"arquivar\":false,\"etiqueta\":\"\"},\"id\":\"33c38719-104d-46e0-8036-77d264960c62\",\"mensagem\":\"Compreendo [CLIENTE]! Quando você diz caro, você está comparando com o que especificamente? Só pra eu entender e poder te ajudar mesmo.\",\"titulo\":\"Negociação\",\"type\":\"txt\"},{\"categoria\":\"\",\"clicked\":0,\"config\":{\"aba\":\"Leads\",\"arquivar\":false,\"etiqueta\":\"\"},\"id\":\"36bcdb5c-cec3-4fc0-ad63-d1191b77263a\",\"mensagem\":\"Olá [CLIENTE], meu nome é [VENDEDOR]. \\nTudo bem? \\nÉ uma alegria para mim poder te ajudar.😀\",\"titulo\":\"Saudação\",\"type\":\"txt\"}],\"initSystem\":true,\"keyCopy\":\"hebrainwatidy\",\"lang\":\"pt\",\"license\":\"KNzVIL+5KBj6JDUF2sQmUytpIVcGQnQ=--Rd4M3qsVinPmSdym--VeITrRPZtbnyet1oIvEatA==\",\"menuItems\":[{\"icon\":\"all\",\"id\":\"edit_tabs\",\"title\":\"Configurações de abas\"},{\"icon\":\"notifications\",\"id\":\"notifications\",\"title\":\"Notificações\"},{\"icon\":\"campaign\",\"id\":\"campaign\",\"title\":\"Envios em Massa\"},{\"icon\":\"automatic_bot\",\"id\":\"automatic_bot\",\"title\":\"Robo de automação\"},{\"icon\":\"cog\",\"id\":\"settings\",\"title\":\"Configurações\"}],\"notes\":[],\"notifications\":[],\"perfil\":[],\"privacySettings\":{\"allMsgs\":false,\"lastMsg\":false,\"mediaGallery\":false,\"mediaPreview\":false,\"names\":false,\"profilePic\":false},\"systemTabs\":[{\"img\":\"all\",\"tag\":\"tab_all\",\"type\":\"system\"},{\"img\":\"unread\",\"tag\":\"tab_unread\",\"type\":\"system\"},{\"img\":\"groups\",\"tag\":\"tab_groups\",\"type\":\"system\"},{\"img\":\"1_1\",\"tag\":\"tab_1_1\",\"type\":\"system\"}],\"userTabs\":[{\"chats\":[],\"tag\":\"Nordeste\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Sul\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Outros Nacionais\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"EUA\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Europa\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"America do Sul\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Caribe\",\"type\":\"user\"}],\"valNegocio\":[],\"zoomCRM\":100}",
        descricao: "Organizando seus clientes com nossa ferramenta você não perderar mais suas oportunidades de vender seus pacotes de viagens. Aproveite para estimular vendas ofertando promoções para destinos de intersse de seus clintes. Não se esqueça de criar respostas rápidas de acordo com seu seguimento e agilizar assim seu atendimento."
      },
      {
        id: "40",
        nome: "Corretor de Imóveis",
        arquivo: "{\"agendaMsg\":[],\"assinatura\":{\"nome\":null},\"categoria\":[{\"format\":\"star\",\"hexColor\":\"#d1e3f3\",\"id\":\"c6a0f455-07e1-4a77-87c3-289520f5c735\",\"name\":\"Negociação💸\"},{\"format\":\"star\",\"hexColor\":\"#bd848a\",\"id\":\"d13958cd-05d1-4638-9d63-3ac5b8d4df7d\",\"name\":\"Mapeamento📝\"},{\"format\":\"star\",\"hexColor\":\"#a7a874\",\"id\":\"ced74504-3c35-4dd8-9076-6a832ffa5634\",\"name\":\"Apresentação🤝\"}],\"ccList\":[],\"contatos\":[],\"crm_peformace\":{\"abas\":15,\"inbox\":15},\"darkMode\":[],\"dataVerif\":\"08/28/2023\",\"events\":[],\"finalizar\":{\"arquivar\":false,\"envTxt\":true,\"txt\":\"*_#Atendimento Finalizado_*\\n\"},\"guardaMsg\":[],\"initSystem\":true,\"keyCopy\":\"Valter-free-testes\",\"lang\":\"pt\",\"license\":\"b74sVcNZseeaXdZYGvlT7mfqrFCOord1KPz0xw==--0Bl+zjZxQlNJ0aZf--Mk1971kkzu4Hpyt93LAhzg==\",\"menuItems\":[],\"notes\":[],\"notifications\":[],\"perfil\":[],\"privacySettings\":{\"allMsgs\":false,\"lastMsg\":false,\"mediaGallery\":false,\"mediaPreview\":false,\"names\":false,\"profilePic\":false},\"systemTabs\":[{\"img\":\"all\",\"tag\":\"tab_all\",\"type\":\"system\"},{\"img\":\"unread\",\"tag\":\"tab_unread\",\"type\":\"system\"},{\"img\":\"groups\",\"tag\":\"tab_groups\",\"type\":\"system\"},{\"img\":\"1_1\",\"tag\":\"tab_1_1\",\"type\":\"system\"}],\"userTabs\":[{\"chats\":[],\"tag\":\"Lancamentos\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Apto\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Casa\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Apto AP\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Casa AP\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Lote\",\"type\":\"user\"}],\"valNegocio\":[],\"zoomCRM\":100}",
        descricao: "Um modelo de funil personalizado para corretores de imóveis super simples e intuitivo."
      },
      {
        id: "41",
        nome: "Clínica de Estética",
        arquivo: "{\"agendaMsg\":[],\"assinatura\":{\"nome\":null},\"categoria\":[{\"format\":\"star\",\"hexColor\":\"#37b591\",\"id\":\"3cc99778-e91b-4dc2-900b-1538a3a02acf\",\"name\":\"APRESENTAÇÃO🤝\"},{\"format\":\"star\",\"hexColor\":\"#7bb986\",\"id\":\"0975acc7-76ca-4a73-a0b3-2da81766649d\",\"name\":\"NEGOCIAÇÃO🤼‍♂️\"},{\"format\":\"star\",\"hexColor\":\"#d78504\",\"id\":\"0eea5a12-b51e-4cd0-b60e-8b8fb9706e94\",\"name\":\"AGENDAMENTO📣\"},{\"format\":\"star\",\"hexColor\":\"#6f9827\",\"id\":\"7ee1ebf8-ada8-4aec-b4bb-643c4a6f077b\",\"name\":\"AVALIAÇÃO♨️\"},{\"format\":\"star\",\"hexColor\":\"#012d2b\",\"id\":\"24641091-3539-4b3a-81c5-ea832098b0ae\",\"name\":\"CLIENTE❤️\"}],\"ccList\":[],\"contatos\":[],\"crm_peformace\":{\"abas\":15,\"inbox\":15},\"darkMode\":[],\"dataVerif\":\"08/28/2023\",\"events\":[],\"finalizar\":{\"arquivar\":false,\"envTxt\":true,\"txt\":\"*_#Atendimento Finalizado_*\\n\"},\"guardaMsg\":[],\"initSystem\":true,\"keyCopy\":\"Valter-free-testes\",\"lang\":\"pt\",\"license\":\"Z/QsyHp56mi1qF0yQqC5Pitc0SfqdoMiAfvVIw==--ziNUGRwMkPkg6g7S--dFdLIIyy/6MPYBjBkGiO7A==\",\"menuItems\":[],\"notes\":[],\"notifications\":[],\"perfil\":[],\"privacySettings\":{\"allMsgs\":false,\"lastMsg\":false,\"mediaGallery\":false,\"mediaPreview\":false,\"names\":false,\"profilePic\":false},\"systemTabs\":[{\"img\":\"all\",\"tag\":\"tab_all\",\"type\":\"system\"},{\"img\":\"unread\",\"tag\":\"tab_unread\",\"type\":\"system\"},{\"img\":\"groups\",\"tag\":\"tab_groups\",\"type\":\"system\"},{\"img\":\"1_1\",\"tag\":\"tab_1_1\",\"type\":\"system\"}],\"userTabs\":[{\"chats\":[],\"tag\":\"Apresentacao\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Negociacao\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Agendamento\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Avaliacao\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Cliente\",\"type\":\"user\"}],\"valNegocio\":[],\"zoomCRM\":100}",
        descricao: "Com esse funil pré configurado sua clínica de estética não perderá mais nenhuma venda!"
      },
      {
        id: "42",
        nome: "Advocacia",
        arquivo: "{\"userTabs\":[{\"chats\":[],\"tag\":\"Tributario\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Trabalhista\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Civel\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Criminal\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Audiencias\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Orcamento Enviado\",\"type\":\"user\"},{\"chats\":[],\"tag\":\"Sentenciado\",\"type\":\"user\"}],\"guardaMsg\":[{\"categoria\":\"\",\"clicked\":0,\"config\":{\"aba\":\"Achou Preco Alto\",\"arquivar\":false,\"etiqueta\":\"\"},\"id\":\"33c38719-104d-46e0-8036-77d264960c62\",\"mensagem\":\"Compreendo [CLIENTE]! Quando você diz caro, você está comparando com o que especificamente? Só pra eu entender e poder te ajudar mesmo.\",\"titulo\":\"Negociação\",\"type\":\"txt\"},{\"categoria\":\"\",\"clicked\":0,\"config\":{\"aba\":\"Leads\",\"arquivar\":false,\"etiqueta\":\"\"},\"id\":\"36bcdb5c-cec3-4fc0-ad63-d1191b77263a\",\"mensagem\":\"Olá [CLIENTE], meu nome é [VENDEDOR]. \\nTudo bem? \\nÉ uma alegria para mim poder te ajudar.😀\",\"titulo\":\"Saudação\",\"type\":\"txt\"}],\"categoria\":[]}",
        descricao: "Seu escritório de Advocacia estará muito mais organizado como esse funil criado para gerenciar melhor seus contatos. Controle de forma simples e personalize como quiser a segmentação de seus clientes com waTidy."
      }
    ];

    // Limpa modelos existentes antes de inserir os novos
    await prisma.modeloCRM.deleteMany({});

    // Insere os novos modelos
    for (const modelo of modelosData) {
      await prisma.modeloCRM.create({
        data: {
          id: modelo.id,
          nome: modelo.nome,
          arquivo: modelo.arquivo,
          descricao: modelo.descricao
        }
      });
    }

    return NextResponse.json({
      success: true,
      message: "Modelos CRM inseridos com sucesso",
      count: modelosData.length
    });
  } catch (error) {
    console.error("Erro ao inserir modelos:", error);
    return NextResponse.json({
      success: false,
      message: "Erro ao inserir modelos CRM",
      error: String(error)
    }, { status: 500 });
  }
} 